from django.test import TestCase

# Create your tests here.
# from deribit_arb_app.test.test_derebit_indicator_annualized_return_spread_builder_test_case import TestDeribitIndicatorAnnualizedReturnSpreadBuilderTestCase
# from deribit_arb_app.test.test_deribit_account_summary_test_case import TestDeribitAccountSummaryTestCase
# from deribit_arb_app.test.test_deribit_api_test_case import TestDeribitApiTestCase
# from deribit_arb_app.test.test_deribit_authentication_test_case import TestDeribitAuthenticationTestCase
# from deribit_arb_app.test.test_deribit_cancel_open_order_test_case import TestDeribitOrderCancelOpenOrderTestCase
# from deribit_arb_app.test.test_deribit_cash_and_carry_strategy_basic_test_case import TestDeribitCashAndCarryStrategyBasicTestCase
# from deribit_arb_app.test.test_deribit_open_orders_test_case import TestDeribitOpenOrdersTestCase
# from deribit_arb_app.test.test_deribit_order_test_case import TestDeribitOrderTestCase
# from deribit_arb_app.test.test_deribit_positions_test_case import TestDeribitPositionsTestCase
# from deribit_arb_app.test.test_deribit_subscribe_instruments_test_case import TestDeribitSubscribeInstrumentsTestCase